"""Port paper.tex into the genuine MDPI (Risks) template: Definitions/mdpi.cls,
Chicago author-date (mdpi_chicago.bst), MDPI front/back-matter macros, BibTeX.

Reuses the existing body verbatim (faithfulness), transforming only:
  - theorem environments lowercase -> Capitalized (MDPI names),
  - \cite -> \citep (author-date),
and replaces the elsarticle front/back matter + manual bibliography with the
MDPI macros + \bibliography{fortuna}.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
L = (ROOT / "paper.tex").read_text().splitlines()


def blk(a, b):  # 1-indexed inclusive
    return "\n".join(L[a - 1:b])


# --- locate boundaries ---
i_abs0 = next(i for i, l in enumerate(L, 1) if "emergencystretch=3em" in l)
i_abs1 = next(i for i, l in enumerate(L, 1) if l.strip() == "\\endgroup")
i_intro = next(i for i, l in enumerate(L, 1) if l.strip() == "\\section{Introduction}")
i_appendix = next(i for i, l in enumerate(L, 1) if l.strip() == "\\appendix")
i_bm = next(i for i, l in enumerate(L, 1) if "\\noindent\\textbf{Supplementary Materials:}" in l)
# back matter is preceded by a \vspace{10pt}; cut appendix block before it
i_bm_start = i_bm
while "\\vspace" not in L[i_bm_start - 1]:
    i_bm_start -= 1

abstract = " ".join(blk(i_abs0 + 1, i_abs1 - 1).split())            # single paragraph
body = blk(i_intro, i_appendix - 1)                                 # sections 1-8
appendix = blk(i_appendix + 1, i_bm_start - 1)                      # appendix content (drop \appendix line)


def transform(s):
    for env in ("theorem", "lemma", "proposition", "definition", "assumption", "corollary", "remark"):
        Cap = env.capitalize()
        s = s.replace("\\begin{%s}" % env, "\\begin{%s}" % Cap)
        s = s.replace("\\end{%s}" % env, "\\end{%s}" % Cap)
    s = s.replace("\\cite{", "\\citep{")     # author-date parenthetical
    return s


body = transform(body)
appendix = transform(appendix)

PREAMBLE = r"""%% MDPI / Risks submission build of "Structure-Preserving Randomization Inference for Decision Timing".
%% Generated by Code/build_mdpi.py from paper.tex. Risks uses Chicago author-date (mdpi_chicago.bst, auto-selected).
\documentclass[risks,article,submit,pdftex,oneauthor]{Definitions/mdpi}

% packages not preloaded by the MDPI class
\usepackage[ruled,linesnumbered]{algorithm2e}
\usepackage{adjustbox}
\usepackage{xurl}% allow long URLs to break at any character so they never overflow the narrow two-column measure
\graphicspath{{ProvidedFigures/}{Charts/}}

\firstpage{1}
\makeatletter \setcounter{page}{\@firstpage} \makeatother
\pubvolume{1}
\issuenum{1}
\articlenumber{0}
\pubyear{2026}
\copyrightyear{2026}
\datereceived{} \dateaccepted{} \datepublished{}

\Title{Structure-Preserving Randomization Inference for Decision Timing}
\Author{Aryan Patel\,\href{https://orcid.org/0009-0008-2097-6170}{\orcidicon}}
\AuthorNames{Aryan Patel}
\address{%
$^{1}$ \quad Independent Researcher; \texttt{ampatel355@gmail.com}}
\corres{Correspondence: \texttt{ampatel355@gmail.com}}

\abstract{__ABSTRACT__}

\keyword{conditional randomization inference; model risk; uncertainty quantification; Monte Carlo methods; sensitivity analysis; backtesting; data snooping; reproducibility}

\JEL{C12; C15; C58; G14}
\MSC{62F03; 62G09; 91G70}

\begin{document}
\maketitle
"""

BACKMATTER = r"""
\supplementary{The online Supplementary Material is available with this article and in the repository cited below. It contains the implementation details (data pipeline, execution and fill model, strategy rules, classifier, Monte Carlo and seed-robustness protocols), the full validation suite (synthetic worlds, positive control, signal-quality experiments), the additional empirical analyses (alternative nulls, multi-asset walk-forward, frequency robustness, per-strategy Monte Carlo distributions, market-regime analysis, seed robustness), the complete figure gallery, and the exact reproduction commands (Sections~S1--S7).}

\authorcontributions{Conceptualization, A.P.; methodology, A.P.; software, A.P.; validation, A.P.; formal analysis, A.P.; investigation, A.P.; data curation, A.P.; writing---original draft preparation, A.P.; writing---review and editing, A.P.; visualization, A.P. The author has read and agreed to the published version of the manuscript.}

\funding{This research received no external funding.}

\institutionalreview{Not applicable.}

\informedconsent{Not applicable.}

\dataavailability{The code and the derived data required to reproduce every table and figure in this article, together with the online Supplementary Material, are openly available in the \emph{Fortuna} repository at \url{https://github.com/ampatel355/FORTUNAFRAMEWORK} and are permanently archived on Zenodo at \url{https://doi.org/10.5281/zenodo.20695539}. The underlying price series (gold futures and the cross-asset universe) were obtained from Yahoo Finance through the \texttt{yfinance} package and are redistributed only in the derived form (regime-labeled OHLCV series, realized trade logs, and per-asset result tables) required for reproduction; raw vendor feeds remain subject to Yahoo Finance's terms of use and can be re-downloaded with the included data loader. All Monte Carlo runs are deterministic under the documented seed protocol.}

\acknowledgments{The author thanks the maintainers of the open-source scientific Python and \TeX{} ecosystems on which this work relies.}

\vspace{6pt}
\noindent\textbf{Use of Generative AI:} During the preparation of this manuscript, the author used generative AI tools (large language model assistants) to help write portions of the analysis code, to review the writing, to correct spelling and grammar, and to improve phrasing. The author reviewed and edited all such output and takes full responsibility for the content of the publication.

\conflictsofinterest{The author declares no conflicts of interest.}
"""

APPENDIX_WRAP = "\n\\appendixtitles{yes}\n\\appendixstart\n\\appendix\n"

TAIL = "\n\\reftitle{References}\n\\bibliography{fortuna}\n\n\\end{document}\n"

out = (PREAMBLE.replace("__ABSTRACT__", abstract) + "\n"
       + body + "\n"
       + BACKMATTER + "\n"
       + APPENDIX_WRAP + appendix + "\n"
       + TAIL)
(ROOT / "paper_mdpi.tex").write_text(out)
print("wrote paper_mdpi.tex (%d lines)" % len(out.splitlines()))
print("abstract words:", len(abstract.split()))
print("Capitalized theorem envs:", sum(out.count("\\begin{%s}" % c) for c in
      ("Proposition", "Definition", "Assumption", "Corollary", "Remark")))
print("\\citep count:", out.count("\\citep{"), "| stray \\cite{ :", len(re.findall(r"\\cite\{", out)))
